#!/usr/bin/env bash

! [[ -f "$1" ]] && echo "Usage: ${0##*/} <main_file_to_watch.lua>" && exit 1
main="$1"; shift

ABORT_WITH_SERVER=0

LUA=${1:-$(which psm || which luajit || which lua5.1 || which lua)}
[[ "$LUA" == nil ]] && LUA=""

ME=$(dirname `readlink -f "$0"`)

if ! lsof -i tcp:20027 &>/dev/null
then
    ${LUA:+"$LUA"} "$ME"/LLive.lua &
fi
echo "Waiting for server..."
sleep 1s
! lsof -i tcp:20027 &>/dev/null && echo "Couldn't start Luce Live Coding server!" && exit 1

echo "Loading main class..."
${LUA:+"$LUA"} "$ME"/LLiveClient.lua "$main"
while true
do
    ((ABORT_WITH_SERVER)) && \
        ! lsof -i tcp:20027 &>/dev/null && echo "Lost contact with Luce Live Coding server - abort" && exit 1

    inotifywait -e modify "$main" &>/dev/null
    ${LUA:+"$LUA"} "$ME"/LLiveClient.lua "$main"
done
